apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-blue
  labels:
    app: example-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
      version: blue
  template:
    metadata:
      labels:
        app: example-app
        version: blue
    spec:
      containers:
      - name: example-app
        image: your-docker-registry/example-app:latest
        ports:
        - containerPort: 8080
